// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7361N-g4WpcKHfDb5WYFsg6vpzClkJFg',
    appId: '1:864476242862:web:3908a4c3a99e1429071e3f',
    messagingSenderId: '864476242862',
    projectId: 'chat-app-3cd2a',
    authDomain: 'chat-app-3cd2a.firebaseapp.com',
    storageBucket: 'chat-app-3cd2a.appspot.com',
    measurementId: 'G-WQYCM7NQ40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQw_oglsj1Ar_ocIm-QgQ6EUQCuvvHsQs',
    appId: '1:864476242862:android:51484fe26748d78f071e3f',
    messagingSenderId: '864476242862',
    projectId: 'chat-app-3cd2a',
    storageBucket: 'chat-app-3cd2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZVOCMVDPQdXDnxNrLR9dbTWKuHhhYVpM',
    appId: '1:864476242862:ios:4433e9d8f108b916071e3f',
    messagingSenderId: '864476242862',
    projectId: 'chat-app-3cd2a',
    storageBucket: 'chat-app-3cd2a.appspot.com',
    iosClientId: '864476242862-jgi39lc6hkamri6uv8lk2a0pk13lklam.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZVOCMVDPQdXDnxNrLR9dbTWKuHhhYVpM',
    appId: '1:864476242862:ios:4433e9d8f108b916071e3f',
    messagingSenderId: '864476242862',
    projectId: 'chat-app-3cd2a',
    storageBucket: 'chat-app-3cd2a.appspot.com',
    iosClientId: '864476242862-jgi39lc6hkamri6uv8lk2a0pk13lklam.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
